### ISSUE TITLE
Not working in Ruby 2.2.0 and 2.3.1

### ISSUE THREAD

**Issue by ribamar-santarosa** [gmodarelli/ruby-deepclone#12]
irb

2.2.0 :001 > require "deep_clone"
 => true 
2.2.0 :002 > o1 = Object.new
 => #Object:0x0000000097c2c8 
2.2.0 :003 > o2 = DeepClone.clone o1
ArgumentError: wrong number of arguments (1 for 0)
        from (irb):3:in clone
        from (irb):3
        from /usr/local/rvm/rubies/ruby-2.2.0/bin/irb:11:in <main>

with 1.9.3 it works OK. With 2.3.\* it doesn't too.

**Comment by balmma** [comment]
Are you using the latest version of ruby_deep_clone (currently 0.7.2)?

It actually seems to work:

mbalmer@laptop-mat:~$ ruby -v
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]
mbalmer@laptop-mat:~$ irb
irb(main):001:0> require "deep_clone"
=> true
irb(main):002:0> o1=Object.new
=> #Object:0x0055f0f459c528
irb(main):003:0> o2=DeepClone.clone o1
=> #Object:0x0055f0f4594210
irb(main):004:0>

**Comment by gmodarelli** [comment]
All specs are running fine for ruby 2.3 and 2.2
