### ISSUE TITLE
Impossible to install the gem under Ruby 2.1

### ISSUE THREAD

**Issue by romikoops** [gmodarelli/ruby-deepclone#3]
It is impossible to install the gem under Ruby 2.1 The error is bellow:

<pre>
gem install ruby_deep_clone -v '0.3.0' 
Building native extensions.  This could take a while...
ERROR:  Error installing ruby_deep_clone:
    ERROR: Failed to build gem native extension.

    /Users/romikoops/.rvm/rubies/ruby-2.1.0/bin/ruby extconf.rb
/Users/romikoops/.rvm/rubies/ruby-2.1.0/bin/ruby: warning: RUBY_FREE_MIN is obsolete. Use RUBY_GC_HEAP_FREE_SLOTS instead.
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling deep_clone.c
deep_clone.c:106:25: error: no member named 'iv_index_tbl' in 'struct RClass'
        st_table *tbl = ROBJECT_IV_INDEX_TBL(object);
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/romikoops/.rvm/rubies/ruby-2.1.0/include/ruby-2.1.0/ruby/ruby.h:784:6: note: expanded from macro 'ROBJECT_IV_INDEX_TBL'
     RCLASS_IV_INDEX_TBL(rb_obj_class(o)) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./deep_clone.h:33:44: note: expanded from macro 'RCLASS_IV_INDEX_TBL'
#define RCLASS_IV_INDEX_TBL(c) (RCLASS(c)->iv_index_tbl)
                                ~~~~~~~~~  ^
1 error generated.
make: *** [deep_clone.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/romikoops/.rvm/gems/ruby-2.1.0@calc-service/gems/ruby_deep_clone-0.3.0 for inspection.
Results logged to /Users/romikoops/.rvm/gems/ruby-2.1.0@calc-service/extensions/x86_64-darwin-12/2.1.0-static/ruby_deep_clone-0.3.0/gem_make.out
</pre>

**Comment by romikoops** [comment]
Other useful info:

<pre>
 calc-service git:(master) ✗ ruby -v
ruby 2.1.0p0 (2013-12-25 revision 44422) [x86_64-darwin12.0]
calc-service git:(master) ✗ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.2.0
  - RUBY VERSION: 2.1.0 (2013-12-25 patchlevel 0) [x86_64-darwin12.0]
  - INSTALLATION DIRECTORY: /Users/romikoops/.rvm/gems/ruby-2.1.0@calc-service
  - RUBY EXECUTABLE: /Users/romikoops/.rvm/rubies/ruby-2.1.0/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/romikoops/.rvm/gems/ruby-2.1.0@calc-service/bin
  - SPEC CACHE DIRECTORY: /Users/romikoops/.gem/specs
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-12
  - GEM PATHS:
     - /Users/romikoops/.rvm/gems/ruby-2.1.0@calc-service
     - /Users/romikoops/.rvm/gems/ruby-2.1.0@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--no-ri --no-rdoc"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/romikoops/.rvm/gems/ruby-2.1.0@calc-service/bin
     - /Users/romikoops/.rvm/gems/ruby-2.1.0@global/bin
     - /Users/romikoops/.rvm/rubies/ruby-2.1.0/bin
     - /Users/romikoops/.rvm/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /usr/local/bin
     - /usr/local/sbin
     - /Users/romikoops/bin
</pre>

**Comment by balmma** [comment]
Fixed with. 0.4.0
