### ISSUE TITLE
Error: `clone': allocator undefined for Symbol (TypeError)

### ISSUE THREAD

**Issue by conscho** [gmodarelli/ruby-deepclone#8]
Hi there,

I get this error when trying to clone a complex object that has a couple of Hashes with symbols in it. Do you have any ideas how to fix this?
Can I provide any infos that might help?

Cheers

**Comment by balmma** [comment]
Hi, which version of Ruby are you using? Cheers Mat

**Comment by conscho** [comment]
I'm using 2.2.1

**Comment by balmma** [comment]
Can you provide a simple example Object that allows reproducing the behaviour?

**Comment by conscho** [comment]
The problem seems to be the usage of `.to_sym` in combination with creating a hash entry like so `hash["some_string".to_sym] = 123`. 

It just took me a while to find out. It seems odd. Here's some copy'paste example:

```
require 'deep_clone'

class SomeClass
  attr_reader :list

  def initialize(hash)
    @list = hash
  end
end

hash = {}
hash["test".to_sym] = [1,2,3]
hash["lala".to_sym] = [4,5,6]
a = SomeClass.new(hash)

DeepClone.clone a
```

**Comment by balmma** [comment]
I added the following test cases to the simple_clone_spec:

```
it 'should clone a hash with non literal symbol keys' do
   foo = {}
   foo["foo".to_sym] = "foo"
   foo["bar".to_sym] = "bar"
   clone = DeepClone.clone foo
   expect(clone.object_id).to_not eql(foo)
   expect(clone).to eql(foo)
end

it 'should clone an object with a hash property' do
   class ClassWithHash
      attr_reader :h
      def initialize(h)
         @h = h
      end
   end

   foo = {}
   foo["foo".to_sym] = "foo"
   foo["bar".to_sym] = "bar"

   obj = ClassWithHash.new foo

   clone = DeepClone.clone obj
   expect(clone.object_id).to_not eql(obj)
   expect(clone.h.object_id).to_not eql(obj.h.object_id)
   expect(clone.h).to eql(obj.h)
   expect(clone.h).to eql(foo)
end
```

It seems to work as expected. Have quite some problems to reproduce the behavior.

**Comment by conscho** [comment]
So you don't get this output just doing copy&paste?

![bildschirmfoto 2015-09-14 um 09 17 07](https://cloud.githubusercontent.com/assets/3217378/9844184/73182740-5ac1-11e5-95d9-9bcb92371f44.png)

**Comment by balmma** [comment]
Ok, now it starts to get really weird. The code runs quite fine inside the rake spec task, but no standalone. Have to investigate that a bit further.

**Comment by diei** [comment]
I have the same problem ("TypeError: allocator undefined for Symbol") in the Rails console. I use Ruby 2.2.3 on Mac OS X 10.10.5.

I tested some combinations and found out that only some hash keys provoke the error:

``` ruby
DeepClone.clone SomeClass.new({esd: 1}) # => error
DeepClone.clone SomeClass.new({lala: 1}) # => error
DeepClone.clone SomeClass.new({abc: 1}) # => runs fine
```

**Comment by internationalbridgeinc** [comment]
Getting the same issue once in a while in a Rails app. I can't tell why sometimes it works and why it will suddenly fail. Restarting the server seems to help, but other times it creates the problem. The requests that fail and succeed are exactly the same.
